
import type { Tour } from './types';

export const tours: Tour[] = [
  {
    id: 'jordan',
    title: 'Jordan Desert Expedition',
    destination: 'Jordan',
    date: 'March 2026',
    duration: '7N / 8D',
    price: 4500,
    description: 'Experience the ancient wonders and desert landscapes of Jordan in a premium 4x4 convoy.',
    itinerary: [
        { day: 1, title: 'Arrival in Amman', description: 'Arrive at Queen Alia International Airport, transfer to your hotel. Welcome dinner and briefing.' },
        { day: 2, title: 'Jerash & Ajloun', description: 'Explore the Roman ruins of Jerash and the historic Ajloun Castle.' },
        { day: 3, title: 'Dead Sea', description: 'Drive to the lowest point on Earth. Float in the buoyant, mineral-rich waters of the Dead Sea.' },
        { day: 4, title: 'Wadi Rum Adventure', description: '4x4 desert safari in Wadi Rum, experiencing its vast, silent landscapes. Overnight in a luxury desert camp.' },
        { day: 5, title: 'Exploring Petra', description: 'Full day exploring the UNESCO World Heritage site of Petra, including the Siq and the Treasury.' },
        { day: 6, title: 'Petra Continues', description: 'Hike up to the Monastery for breathtaking views. Further exploration of the ancient city.' },
        { day: 7, title: 'Back to Amman', description: 'Drive back to Amman via the scenic Desert Highway.' },
        { day: 8, title: 'Departure', description: 'Transfer to the airport for your flight home.' },
      ],
    accommodation: 'Luxury hotels and desert camps.',
    pointsOfInterest: ['Petra', 'Wadi Rum', 'Dead Sea'],
    image: 'expedition-jordan',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    status: 'Hot Deal',
    rating: 4.7,
    fullDate: '21-28 Mar, 2026',
    driveType: 'Guided',
    level: 'Beginner'
  },
  {
    id: 'south-africa',
    title: 'South Africa Grand Drive',
    destination: 'South Africa',
    date: 'March 2026',
    duration: '9N / 10D',
    price: 5200,
    description: 'Journey from Cape Town through the Garden Route. Experience wine country, coastal beauty, and wildlife reserves.',
    itinerary: [
        { day: 1, title: 'Cape Town Arrival', description: 'Arrive in Cape Town, transfer to your hotel. Explore the V&A Waterfront.' },
        { day: 2, title: 'Cape Peninsula Tour', description: 'Full-day tour of the Cape Peninsula, including Chapman\'s Peak Drive and the Cape of Good Hope.'},
        { day: 3, title: 'Winelands', description: 'Explore the famous winelands of Stellenbosch and Franschhoek with wine tasting sessions.'},
        { day: 4, title: 'Garden Route: Oudtshoorn', description: 'Drive along the scenic Route 62 to Oudtshoorn, the ostrich capital of the world.'},
        { day: 5, title: 'Garden Route: Knysna', description: 'Travel to Knysna, explore the Knysna Heads and enjoy a lagoon cruise.'},
        { day: 6, title: 'Safari in a Private Reserve', description: 'Head to a private game reserve for an afternoon safari drive.'},
        { day: 7, title: 'Full Day Safari', description: 'Enjoy morning and afternoon safari drives, searching for the Big Five.'},
        { day: 8, title: 'Flight to Johannesburg', description: 'Fly from George to Johannesburg. Explore the Apartheid Museum.'},
        { day: 9, title: 'Departure', description: 'Transfer to the airport for your flight home.'},
    ],
    accommodation: '5-star hotels and safari lodges.',
    pointsOfInterest: ['Cape Town', 'Garden Route', 'Kruger National Park'],
    image: 'expedition-sa',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    distance: 2200,
    level: 'Intermediate',
    status: 'Trending',
    rating: 4.8,
    fullDate: '8-17 Mar, 2026',
    driveType: 'Self-Drive'
  },
  {
    id: 'kyrgyzstan',
    title: 'Kyrgyzstan',
    destination: 'Kyrgyzstan',
    date: 'June 2026',
    duration: '10 Days',
    price: 4800,
    description: 'Explore the stunning mountain passes and pristine lakes of Central Asia\'s hidden gem.',
    itinerary: [],
    accommodation: 'Hotels and traditional yurts.',
    pointsOfInterest: ['Issyk-Kul Lake', 'Song-Kul Lake', 'Ala Archa National Park'],
    image: 'tour-kyrgyzstan',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    status: 'Upcoming',
    rating: 4.6,
    fullDate: '10-19 June, 2026',
    driveType: 'Guided',
    level: 'Adventure'
  },
  {
    id: 'spiti-valley',
    title: 'Spiti Valley Expedition',
    destination: 'India',
    date: 'July 2026',
    duration: '7 Days',
    price: 3500,
    description: 'Conquer the high-altitude desert mountains of India\'s most challenging driving route.',
    itinerary: [],
    accommodation: 'Hotels and guesthouses.',
    pointsOfInterest: ['Key Monastery', 'Chandratal Lake', 'Kunzum Pass'],
    image: 'tour-spiti',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    status: 'Upcoming',
    rating: 4.7,
    fullDate: '5-11 July, 2026',
    driveType: 'Self-Drive',
    level: 'Expert'
  },
  {
    id: 'namibia',
    title: 'Namibia',
    destination: 'Namibia',
    date: 'August 2026',
    duration: '12 Days',
    price: 6200,
    description: 'Conquer the world\'s highest sand dunes, explore the Skeleton Coast, and witness incredible desert wildlife.',
    itinerary: [],
    accommodation: 'Luxury lodges and desert camps.',
    pointsOfInterest: ['Sossusvlei', 'Etosha National Park', 'Skeleton Coast'],
    image: 'mega-tour-namibia',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    distance: 3100,
    level: 'Adventure',
    status: 'Trending',
    rating: 4.9,
    fullDate: '1-12 Aug, 2026',
    driveType: 'Self-Drive'
  },
  {
    id: 'iceland',
    title: 'Iceland Ring Road',
    destination: 'Iceland',
    date: 'May 2026',
    duration: '8N / 9D',
    price: 7500,
    description: 'Complete the legendary Ring Road through volcanic landscapes, glaciers, geysers, and the magical Northern Lights season.',
    itinerary: [
        { day: 1, title: 'Arrival in Reykjavik', description: 'Arrive at Keflavik airport and transfer to Reykjavik. Explore the city.' },
        { day: 2, title: 'Golden Circle', description: 'Explore Thingvellir National Park, Gullfoss waterfall, and the Geysir geothermal area.'},
        { day: 3, title: 'South Coast', description: 'Visit Seljalandsfoss and Skogafoss waterfalls, and the black sand beach of Reynisfjara.'},
        { day: 4, title: 'Jokulsarlon Glacier Lagoon', description: 'Drive to the famous glacier lagoon and Diamond Beach.'},
        { day: 5, title: 'East Fjords', description: 'Drive through the scenic and remote East Fjords.'},
        { day: 6, title: 'Lake Myvatn', description: 'Explore the geothermal wonders of the Lake Myvatn area.'},
        { day: 7, title: 'Akureyri', description: 'Visit the "Capital of the North" and enjoy its botanical gardens and architecture.'},
        { day: 8, title: 'Return to Reykjavik', description: 'Drive back to Reykjavik for a final evening.'},
        { day: 9, title: 'Departure', description: 'Transfer to the airport for your flight home.'},
    ],
    accommodation: 'Premium hotels and lodges.',
    pointsOfInterest: ['Ring Road', 'Glacier Lagoon', 'Geysers', 'Northern Lights'],
    image: 'tour-iceland-2',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    distance: 1850,
    level: 'Beginner',
    status: 'New',
    rating: 4.9,
    fullDate: '15-23 May, 2026',
    driveType: 'Self-Drive'
  },
  {
    id: 'thailand',
    title: 'Thailand',
    destination: 'Thailand',
    date: 'November 2026',
    duration: '9 Days',
    price: 4300,
    description: 'Experience the perfect blend of culture, beaches, and mountain roads in Southeast Asia.',
    itinerary: [],
    accommodation: 'Luxury resorts and boutique hotels.',
    pointsOfInterest: ['Chiang Mai', 'Mae Hong Son Loop', 'Phuket'],
    image: 'tour-thailand',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    status: 'Upcoming',
    rating: 4.4,
    fullDate: '12-20 Nov, 2026',
    driveType: 'Guided',
    level: 'Intermediate'
  },
  {
    id: 'new-zealand',
    title: 'New Zealand Overland',
    destination: 'New Zealand',
    date: 'April 2026',
    duration: '11N / 12D',
    price: 8200,
    description: 'Discover the stunning landscapes of both the North and South Islands, from geothermal wonders to majestic fjords.',
    itinerary: [],
    accommodation: 'Luxury lodges and boutique hotels.',
    pointsOfInterest: ['Fiordland', 'Queenstown', 'Rotorua'],
    image: 'tour-nz-2',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    level: 'Intermediate',
    status: 'Trending',
    rating: 4.9,
    fullDate: '4-15 Apr, 2026',
    driveType: 'Guided'
  },
  {
    id: 'road-to-london',
    title: 'Road to London',
    destination: 'India - UK',
    date: 'April 2026',
    duration: '64N / 65D',
    price: 25000,
    description: 'The ultimate overland expedition from India to London, crossing 18 countries in an epic journey of a lifetime.',
    itinerary: [],
    accommodation: 'Mix of hotels and camps.',
    pointsOfInterest: ['Silk Road', 'European Capitals', 'Diverse Cultures'],
    image: 'expedition-london',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    level: 'Advanced',
    status: 'Epic Journey',
    rating: 4.8,
    fullDate: '17 Apr - 20 Jun',
    driveType: 'Self-Drive'
  },
  {
    id: 'australia-outback',
    title: 'Australian Outback',
    destination: 'Australia',
    date: 'June 2026',
    duration: '13N / 14D',
    price: 6800,
    description: 'Explore the vast and rugged beauty of the Australian Outback from Sydney to Uluru.',
    itinerary: [],
    accommodation: 'Lodges and authentic outback stations.',
    pointsOfInterest: ['Blue Mountains', 'Flinders Ranges', 'Uluru'],
    image: 'tour-australia',
    level: 'Intermediate',
    status: 'Adventure',
    rating: 4.6,
    fullDate: '1-14 Jun, 2026',
    driveType: 'Guided'
  },
  {
    id: 'patagonia-explorer',
    title: 'Patagonia Explorer',
    destination: 'Argentina - Chile',
    date: 'July 2026',
    duration: '10N / 11D',
    price: 7900,
    description: 'Journey to the end of the world, crossing from Argentina to Chile through stunning Patagonia.',
    itinerary: [],
    accommodation: 'Boutique hotels and mountain lodges.',
    pointsOfInterest: ['Torres del Paine', 'Perito Moreno Glacier', 'Fitz Roy'],
    image: 'tour-patagonia',
    level: 'Advanced',
    status: 'Trending',
    rating: 5.0,
    fullDate: '18-28 Jul, 2026',
    driveType: 'Self-Drive'
  },
  {
    id: 'norwegian-fjords',
    title: 'Norwegian Fjords',
    destination: 'Norway',
    date: 'August 2026',
    duration: '6N / 7D',
    price: 5500,
    description: 'Drive along the iconic fjords of Norway from Oslo to Bergen, experiencing breathtaking views.',
    itinerary: [],
    accommodation: 'Luxury hotels with fjord views.',
    pointsOfInterest: ['Geirangerfjord', 'Trollstigen', 'Atlantic Ocean Road'],
    image: 'tour-norway',
    level: 'Beginner',
    status: 'Luxury',
    rating: 4.8,
    fullDate: '5-11 Aug, 2026',
    driveType: 'Guided'
  },
  {
    id: 'morocco-imperial',
    title: 'Morocco Imperial Cities',
    destination: 'Morocco',
    date: 'September 2026',
    duration: '8N / 9D',
    price: 4800,
    description: 'From the bustling souks of Marrakech to the vast Sahara desert, a journey of color and culture.',
    itinerary: [],
    accommodation: 'Riads and luxury desert camps.',
    pointsOfInterest: ['Marrakech', 'Fes', 'Sahara Desert', 'Ait Benhaddou'],
    image: 'tour-morocco',
    level: 'Intermediate',
    status: 'Hot Deal',
    rating: 4.7,
    fullDate: '12-20 Sep, 2026',
    driveType: 'Self-Drive'
  }
];
