
import type { Tour } from './types';

export const tours: Tour[] = [
  {
    id: 'spiti-valley',
    title: 'Spiti Valley Winter Expedition',
    destination: 'India',
    date: 'March 2026',
    duration: '8N / 9D',
    price: 3500,
    description: 'Conquer the high-altitude desert mountains of India\'s most challenging driving route.',
    itinerary: [],
    accommodation: 'Hotels and guesthouses.',
    pointsOfInterest: ['Kaza', 'Chitkul', 'Tabo', 'Kalpa', 'Snow Driving'],
    image: 'tour-spiti',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    status: 'Upcoming',
    rating: 4.7,
    fullDate: '21 – 29 Mar, 2026',
    driveType: 'Self-Drive 4x4 (Extreme Winter)',
    driveCategory: 'Self-Drive',
    level: 'Expert',
    brochureUrl: '/itinerary/Spiti_Premium_Winter Expedition_Self_Drive.pdf'
  },
  {
    id: 'thailand',
    title: 'Thailand Self-Drive Experience',
    destination: 'Thailand',
    date: 'March 2026',
    duration: '8N / 9D',
    price: 4300,
    distance: 1600,
    description: 'Experience the perfect blend of culture, beaches, and mountain roads in Southeast Asia.',
    itinerary: [],
    accommodation: 'Luxury resorts and boutique hotels.',
    pointsOfInterest: ['Bangkok', 'Hua Hin', 'Koh Samui', 'Krabi', 'Phuket'],
    image: 'tour-thailand',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    status: 'Trending',
    rating: 4.4,
    fullDate: '29 Mar, 2026',
    driveType: 'Self-Drive SUV',
    driveCategory: 'Self-Drive',
    level: 'Beginner',
    brochureUrl: '/itinerary/Thailand_Brochure.pdf'
  },
  {
    id: 'jordan',
    title: 'Jordan Desert Expedition',
    destination: 'Jordan',
    date: 'April 2026',
    duration: '7N / 8D',
    price: 4500,
    distance: 1000,
    description: 'Experience the ancient wonders and desert landscapes of Jordan in a premium 4x4 convoy.',
    itinerary: [
        { day: 1, title: 'Arrival in Amman', description: 'Arrive at Queen Alia International Airport, transfer to your hotel. Welcome dinner and briefing.' },
        { day: 2, title: 'Jerash & Ajloun', description: 'Explore the Roman ruins of Jerash and the historic Ajloun Castle.' },
        { day: 3, title: 'Dead Sea', description: 'Drive to the lowest point on Earth. Float in the buoyant, mineral-rich waters of the Dead Sea.' },
        { day: 4, title: 'Wadi Rum Adventure', description: '4x4 desert safari in Wadi Rum, experiencing its vast, silent landscapes. Overnight in a luxury desert camp.' },
        { day: 5, title: 'Exploring Petra', description: 'Full day exploring the UNESCO World Heritage site of Petra, including the Siq and the Treasury.' },
        { day: 6, title: 'Petra Continues', description: 'Hike up to the Monastery for breathtaking views. Further exploration of the ancient city.' },
        { day: 7, title: 'Back to Amman', description: 'Drive back to Amman via the scenic Desert Highway.' },
        { day: 8, title: 'Departure', description: 'Transfer to the airport for your flight home.' },
      ],
    accommodation: 'Luxury hotels and desert camps.',
    pointsOfInterest: ['Petra', 'Wadi Rum', 'Dead Sea', 'Aqaba'],
    image: 'expedition-jordan',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    status: 'Hot Deal',
    rating: 4.7,
    fullDate: '10 Apr, 2026',
    driveType: 'Guided Self-Drive Convoy',
    driveCategory: 'Guided',
    level: 'Beginner'
  },
  {
    id: 'south-africa',
    title: 'South Africa Self-Drive Tour',
    destination: 'South Africa',
    date: 'April 2026',
    duration: '8N / 9D',
    price: 4600,
    distance: 1800,
    description: 'Discover the breathtaking beauty of the Garden Route and beyond on this scenic self-drive adventure.',
    itinerary: [],
    accommodation: 'Boutique hotels and safari lodges.',
    pointsOfInterest: ['Garden Route', 'Cape Town', 'Kruger National Park'],
    image: 'tour-south-africa',
    brochureUrl: '/itinerary/South-Africa-2026.pdf',
    fullDate: '24 Apr, 2026',
    driveType: 'Self-Drive SUV',
    driveCategory: 'Self-Drive',
    level: 'Intermediate',
    status: 'New',
    rating: 4.8
  },
  {
    id: 'kyrgyzstan',
    title: 'Kyrgyzstan Self-Drive Adventure',
    destination: 'Kyrgyzstan',
    date: 'May 2026',
    duration: '8N / 9D',
    price: 4800,
    distance: 1900,
    description: 'Explore the stunning mountain passes and pristine lakes of Central Asia\'s hidden gem.',
    itinerary: [],
    accommodation: 'Hotels and traditional yurts.',
    pointsOfInterest: ['Son-Kul Lake', 'Issyk-Kul', 'Altyn Arashan'],
    image: 'tour-kyrgyzstan',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    status: 'Upcoming',
    rating: 4.6,
    fullDate: '22 May, 2026',
    driveType: 'Self-Drive 4x4 Expedition',
    driveCategory: 'Self-Drive',
    level: 'Adventure',
    brochureUrl: '/itinerary/Kyrgyzstan_Self_Drive_Adventure.pdf'
  }
];
