import type { Tour } from './types';

export const tours: Tour[] = [
  {
    id: 'south-africa',
    title: 'South Africa Self-Drive Tour',
    destination: 'South Africa',
    date: 'April 2026',
    duration: '8N / 9D',
    price: 4600,
    distance: 1800,
    description: 'Discover the breathtaking beauty of the Garden Route and beyond on this scenic self-drive adventure.',
    itinerary: [],
    accommodation: 'Boutique hotels and safari lodges.',
    pointsOfInterest: ['Garden Route', 'Cape Town', 'Kruger National Park'],
    image: 'tour-south-africa',
    brochureUrl: '/itinerary/South-Africa-2026.pdf',
    fullDate: '24 Apr, 2026',
    driveType: 'Self-Drive SUV',
    driveCategory: 'Self-Drive',
    level: 'Intermediate',
    status: 'New',
    rating: 4.8
  },
  {
    id: 'spiti-valley',
    title: 'Spiti Valley Summer Expedition',
    destination: 'India',
    date: 'April 2026',
    duration: '9N / 10D',
    price: 115000,
    description: 'Experience the wild heart of the Himalayas. Step into a world of raw landscapes, ancient monasteries, and roads that test your spirit.',
    longDescription: "Step into the wild heart of the Himalayas with the Spiti Summer Self-Drive Expedition — a 10-day adventure where every turn brings raw landscapes, ancient monasteries, remote villages, river crossings, and roads that test your spirit. From the last village of India at Chitkul to the surreal cold desert of Kaza, from the curves of Kinnaur to the towering peaks of Kalpa, this is not just a trip — it's a story you will tell for the rest of your life. Built for true explorers, this expedition combines adrenaline, breathtaking scenery, and the unmatched thrill of driving your own 4x4 through one of India’s most dramatic mountain terrains.",
    itinerary: [],
    accommodation: 'Boutique hotels, luxury camps, and traditional guesthouses.',
    pointsOfInterest: ['Chitkul', 'Kalpa', 'Kaza', 'Tabo', 'Hikkim', 'Komic', 'Langza', 'Kunzum Pass'],
    image: 'tour-spiti',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    status: 'Upcoming',
    rating: 4.9,
    fullDate: 'April 28 – May 7, 2026',
    driveType: 'Self Drive 4x4',
    driveCategory: 'Self-Drive',
    level: 'Adventure',
    brochureUrl: '/itinerary/Spiti_Summer_Expedition.pdf'
  },
  {
    id: 'thailand-self-drive',
    title: 'Thailand Self-Drive Experience',
    destination: 'Thailand',
    date: 'May 2026',
    duration: '6 Nights / 7 Days',
    price: 160000,
    distance: 1200,
    description: 'Experience Thailand on a 6-night, 7-day self-drive coastal adventure that combines lively cities, tropical beaches, and scenic highway drives.',
    itinerary: [],
    accommodation: 'Luxury resorts and boutique hotels.',
    pointsOfInterest: ['Bangkok', 'Chumphon', 'Krabi', 'Phuket', 'James Bond Island'],
    image: 'tour-thailand',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    status: 'Trending',
    rating: 4.4,
    fullDate: 'May 1 – May 7, 2026',
    driveType: 'Self Drive SUV',
    driveCategory: 'Self-Drive',
    level: 'Beginner',
    brochureUrl: '/itinerary/Thailand_Brochure.pdf'
  },
  {
    id: 'kyrgyzstan',
    title: 'Kyrgyzstan Self-Drive Adventure',
    destination: 'Kyrgyzstan',
    date: 'June 2026',
    duration: '8N / 9D',
    price: 271000,
    distance: 1900,
    description: 'Step into the wild, untouched landscapes of Central Asia. A 9-day self-drive adventure through mountain passes and alpine lakes.',
    itinerary: [],
    accommodation: 'Hotels and traditional yurts.',
    pointsOfInterest: ['Bishkek – Ala-Too Square', 'Issyk-Kul Lake', 'Son-Kul Lake', 'Skazka Canyon', 'Altyn Arashan Valley'],
    image: 'tour-kyrgyzstan',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    status: 'Upcoming',
    rating: 4.6,
    fullDate: 'June 2026',
    driveType: 'Self-Drive 4x4 Expedition',
    driveCategory: 'Self-Drive',
    level: 'Adventure',
    brochureUrl: '/itinerary/Kyrgyzstan_Self_Drive_Adventure.pdf'
  }
];
